name: Android CI/CD

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create Google Services JSON File
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./src/fusion1-events/app/google-services.json

    - name: Build with Gradle
      working-directory: ./src/fusion1-events
      run: gradle build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_artifact
        path: ./src/fusion1-events/app/build/outputs/apk/**/*.apk
        overwrite: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./src/fusion1-events/app/google-services.json
      
      - name: Unit Test
        working-directory: ./src/fusion1-events
        run: gradle testDebugUnitTest

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v4
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: test_artifact
          path: app/build/test-results # path to where the xml test results are stored
          overwrite: true

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create Google Services JSON File
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./src/fusion1-events/app/google-services.json

    - name: Run Linter
      working-directory: ./src/fusion1-events
      run: gradle lint
      continue-on-error: false

    - name: Upload Lint Results
      uses: actions/upload-artifact@v4
      with:
        name: lint_artifact
        path: /home/runner/work/fusion1-events/fusion1-events/src/fusion1-events/app/build/reports/lint-results-debug.html
        overwrite: true
