name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x /home/runner/work/fusion1-events/fusion1-events/src/fusion1-events/gradle/gradlew
    - name: Build with Gradle
      run: /home/runner/work/fusion1-events/fusion1-events/src/fusion1-events/gradle/gradlew build

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Run Android Lint
      uses: yutailang0119/action-android-lint@v4.0.0
      with:
        report-path: build/reports/*.xml
        follow-symbolic-links: false
        ignore-warnings: false
